config/routes.rb
PlaneFinder::Application.routes.draw do
  devise_for :users
  resource :user do
    resources :planes
  end
  
  resources :schools
  
  resources :planes do
    get 'search', :on => :collection
    get 'claim', :on => :member
  end

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/legal',   to: 'static_pages#legal'
  match '/contact', to: 'static_pages#contact'

end

app/models/plane.rb
class Plane
  include Mongoid::Document
  # include Mongoid::FullTextSearch
  include Geocoder::Model::Mongoid
  resourcify
  
  CATEGORIES = %w( Land Sea Amphibian )
  ENDORSEMENTS = [ "High performance", "Complex", "Tailwheel", "Acrobatics" ]
  AIRCRAFT_TYPES = [ "Glider", "Balloon", "Blimp/Dirigible", "Fixed wing single engine", "Fixed wing multi engine", "Rotorcraft", "Weight-shift-control", "Powered Parachute", "Gyroplane" ]
  ENGINE_TYPES = [ "None", "Reciprocating", "Turbo-prop", "Turbo-shaft", "Turbo-jet", "Turbo-fan", "Ramjet", "2 Cycle", "4 Cycle", "Unknown", "Electric", "Rotary" ]

  attr_accessible :image_url, :base_airport, :name, :code, :category, :endorsements, :tail_number, :notes_text,
                  :rental_amount, :rental_type, :tags, :manufacturer, :model, :year, :school_id,
                  :category_value, :endorsement_values, :aircraft_type_value, :engine_type_value
  
  geocoded_by :address               # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  
  belongs_to :school, inverse_of: :plane

  field :tail_number
  field :manufacturer
  field :model
  field :model_name
  field :model_code
  field :category, type: Integer, default: 1
  field :cert_type, type: Integer
  field :engines, type: Integer, default: 1
  field :seats, type: Integer
  field :weight, type: Integer
  field :hp, type: Integer
  field :thrust, type: Integer
  field :year, type: Integer
  field :aircraft_type, type: Integer, default: 4
  field :engine_type, type: Integer, default: 1
  embeds_one :owner  
    
  field :image_url, type: String
  field :base_airport, type: String
  field :name, type: String
  field :code, type: String
  field :endorsements, type: Array, default: []
  field :notes_text, type: String
  field :headline, type: String
  field :rental_amount, type: BigDecimal
  field :rental_type, type: String, default: "wet"
  field :external_url, type: String

  field :coordinates, :type => Array
  field :address, type: String
  field :tags, type: String

  index({ tail_number: 1}, { unique: true })
  # index base_airport: 1
  # index make: 1
  # index :model => 1

  validates :tail_number, uniqueness: true, allow_blank: true
 
  def endorsement_values
    endorsements.map { |v| ENDORSEMENTS[v] }
  end
  
  def endorsement_values= values
    self.endorsements = values.reject!(&:empty?).map { |v| ENDORSEMENTS.index(v) }
  end
  
  def category_value
    CATEGORIES[category - 1]
  end
  
  def category_value= value
    self.category = CATEGORIES.index(value) + 1
  end
  
  def aircraft_type_value
    AIRCRAFT_TYPES[aircraft_type - 1]
  end
  
  def aircraft_type_value= value
    self.aircraft_type = AIRCRAFT_TYPES.index(value) + 1
  end
  
  def engine_type_value
    ENGINE_TYPES[engine_type]
  end
  
  def engine_type_value= value
    self.engine_type = ENGINE_TYPES.index(value)
  end
  
  def rental
    return "" unless rental_amount 
    "#{rental_amount}/hr #{rental_type}"
  end
  
  def abbreviated_type
    return "ASEL" if category==1 and aircraft_type==4
    return "AMEL" if category==1 and aircraft_type==5
    return "ASES" if category==2 and aircraft_type==4
    return "AMES" if category==2 and aircraft_type==5
    return "Helicopter" if aircraft_type==6
    "#{Plane::AIRCRAFT_TYPES[aircraft_type-1]} #{Plane::CATEGORIES[category-1]}"
  end
  
  def featured?
    true
  end
  
  def featured_until
    Date.today + 1.month
  end
  
  def listing_incomplete?
    return true if rental_amount.blank?
    return true if school.blank?
    return true if base_airport.blank?
    return false
  end
  
end

class Owner
  include Mongoid::Document

  field :street1
  field :street2
  field :city
  field :state
  field :zipcode
  
  embedded_in :plane
end

app/controllers/planes_controller.rb
class PlanesController < ApplicationController
  respond_to :html, :json
  
  before_filter :authenticate_user!, except: [ :search, :show ]
  
  def index

    selection = current_user.planes
    selection = current_user.school.planes if current_user.school
    selection = Plane.all if current_user.admin
    
    # reset the filter if keywords changed
    @filter = Filter.new(params[:filter])

    case @filter.query
    when /^N[1-9][0-9]{0,4}$|^N[1-9][0-9]{0,3}[A-Z]$|^N[1-9][0-9]{0,2}[A-Z]{2}$/i
      selection = Plane.where(tail_number: @filter.query[1..-1].upcase)
    when /^K\w{3,4}$/i
      selection = Plane.where(base_airport: @filter.query.upcase)
    when /^\w{3,4}$/i
      selection = Plane.where(base_airport: "K#{@filter.query.upcase}")
      selection = Plane.near(@filter.query) if selection.count == 0
    when present?
      selection = Plane.near(@filter.query)
    end

    @category_options = selection.distinct(:category).sort.map { |i| Plane::CATEGORIES[i-1] }
    @aircraft_type_options = selection.distinct(:aircraft_type).sort.map { |i| Plane::AIRCRAFT_TYPES[i-1] }
    @engine_type_options = selection.distinct(:engine_type).sort.map { |i| Plane::ENGINE_TYPES[i-1] }
    @endorsement_options = selection.distinct(:endorsements).sort.map { |i| Plane::ENDORSEMENTS[i] }

    selection = filter_endorsements(selection) if @filter.endorsements
    selection = filter_categories(selection) if @filter.categories
    selection = filter_aircraft_types(selection) if @filter.aircraft_types
    selection = filter_engine_types(selection) if @filter.engine_types
    
    @planes = selection.page(params[:page])
    respond_with @planes
  end

  def show 
    if params[:id].upcase =~ /^[1-9][0-9]{0,4}$|^[1-9][0-9]{0,3}[A-Z]$|^[1-9][0-9]{0,2}[A-Z]{2}$/
      @plane = Plane.find_by(tail_number: params[:id].upcase)
    else
      @plane = Plane.find(params[:id])
    end
    respond_with @plane
  end
  
  def edit
    @plane = Plane.where(tail_number: params[:id].upcase).first if params[:id] =~ /^[1-9][0-9]{0,4}$|^[1-9][0-9]{0,3}[A-Z]$|^[1-9][0-9]{0,2}[A-Z]{2}$/i
    @plane = @plane || Plane.find(params[:id])
    
    respond_with @plane do |format|
      format.json { render :layout => false, :text => @plane.to_json }
    end
  end

  def update
    @plane = Plane.find(params[:id])
    @plane.address = Geocoder.address(params[:plane][:base_airport])
    @plane.update_attributes(params[:plane])
    render "show", layout: false
    
    # if @plane.update_attributes(params[:plane])
    #   flash[:success] = "Airplane information updated"
    #   redirect_to planes_path
    # else
    #   render 'edit'
    # end
  end
  
  def new
    @plane = Plane.new
    respond_with @plane do |format|
      format.html { render :layout => false }
      format.json { render :layout => false, :text => @plane.to_json }
    end
  end
  
  def create
    @plane = Plane.new(params[:plane])
    @plane.address = Geocoder.address(params[:plane][:base_airport])
    if @plane.save
      flash[:success] = t("plane.created")
      redirect_to planes_path
    else
      render 'new'
    end
  end

  def destroy
    @plane = Plane.find(params[:id])
    @plane.destroy

    respond_to do |format|
      format.html { redirect_to planes_url }
      format.json { head :no_content }
    end
  end
  
  def search
    # results = Plane.near(params[:search])
    # 
    # @planes = results.page(params[:page])
    # @airports = results.map { |plane| plane.base_airport.upcase }.uniq
    # @models = [] # @planes.map { |plane| plane.model.humanize }.uniq
    # 
    selection = Plane.all
    
    # reset the filter if keywords changed
    params[:filter] ||= { query: params[:search] }
    @filter = Filter.new(params[:filter])

    case @filter.query
    when /^N[1-9][0-9]{0,4}$|^N[1-9][0-9]{0,3}[A-Z]$|^N[1-9][0-9]{0,2}[A-Z]{2}$/i
      selection = Plane.where(tail_number: @filter.query[1..-1].upcase)
    when /^K\w{3,4}$/i
      selection = Plane.where(base_airport: @filter.query.upcase)
    when /^\w{3,4}$/i
      selection = Plane.where(base_airport: "K#{@filter.query.upcase}")
      selection = Plane.near(@filter.query) if selection.count == 0
    else
      selection = Plane.near(@filter.query)
    end


    # @category_options = selection.distinct(:category).sort.map { |i| Plane::CATEGORIES[i-1] }
    # @aircraft_type_options = selection.distinct(:aircraft_type).sort.map { |i| Plane::AIRCRAFT_TYPES[i-1] }
    # @engine_type_options = selection.distinct(:engine_type).sort.map { |i| Plane::ENGINE_TYPES[i-1] }
    @endorsement_options = selection.distinct(:endorsements).sort.map { |i| Plane::ENDORSEMENTS[i] }
    @airport_options = selection.distinct(:base_airport).sort
    
    @filter.airports = @airport_options unless params[:filter][:previous_query] == params[:filter][:query]
    
    selection = filter_endorsements(selection) if @filter.endorsements
    selection = filter_airports(selection) if @filter.airports
    
    # selection = filter_categories(selection) if @filter.categories
    # selection = filter_aircraft_types(selection) if @filter.aircraft_types
    # selection = filter_engine_types(selection) if @filter.engine_types
    
    @planes = selection.page(params[:page])
    respond_with @planes    
    
    
    
    
  end

  def claim
    @plane = Plane.where(tail_number: params[:id].upcase).first if params[:id] =~ /^[1-9][0-9]{0,4}$|^[1-9][0-9]{0,3}[A-Z]$|^[1-9][0-9]{0,2}[A-Z]{2}$/i
    
  end
  
  private
  
  def filter_endorsements scope
    return scope if @filter.endorsements.length == @endorsement_options.length + 1
    included_values = @filter.endorsements.reject { |c| c.empty? }.inject([{endorsements:[]}]) { |s,e| s << { endorsements: Plane::ENDORSEMENTS.index(e) } }
    # included_values = (0..3).select { |v| @filter.endorsements.include?(Plane::ENDORSEMENTS[v]) }
    scope.any_of(included_values)
  end

  def filter_airports scope
    scope.any_in(base_airport: @filter.airports)
  end
  
  def filter_categories scope
    return scope if @filter.categories.length == @category_options.length + 1
    included_values = @filter.categories.reject { |c| c.empty? }.map { |e| Plane::CATEGORIES.index(e) + 1 }
    scope.any_in(category: included_values)
  end

  def filter_aircraft_types scope
    return scope if @filter.aircraft_types.length == @aircraft_type_options.length + 1
    included_values = @filter.aircraft_types.reject { |c| c.empty? }.map { |e| Plane::AIRCRAFT_TYPES.index(e) + 1 }
    scope.any_in(aircraft_type: included_values)
  end
  
  def filter_engine_types scope
    return scope if @filter.engine_types.length == @engine_type_options.length + 1
    included_values = @filter.engine_types.reject { |c| c.empty? }.map { |e| Plane::ENGINE_TYPES.index(e) }
    scope.any_in(engine_type: included_values)
  end

end

app/helpers/planes_helper.rb
module PlanesHelper
  
  def formatted_name(plane)
    "#{plane.year} #{plane.make} #{plane.model}"
  end
    
  def formatted_cost(plane)
    "$#{sprintf("%5.0f",plane.rental_amount)}/hr #{plane.rental_type}"
  end

  def rental_text(rental_amount)
    return "$#{rental_amount.to_i}/hr" if rental_amount.to_i > 0
    return I18n.t("views.planes.rental_amount_na")
  end
  
end

app/views/planes/_plane.html.erb
<div class="row-fluid plane">
  <div class="span2">
    <%= image_tag 'anon_plane_50x60.png', class: 'profile-image' %>
  </div>
  <div class="span8">
    <h4><%= plane.year %> <%= plane.manufacturer.titleize %> <%= plane.name %> <%= plane.model %></h4>

<% if plane.featured? %>
    <div class="row-fluid">

      <div class="span6">
        <% if plane.headline %>
          <p><strong><%= plane.headline %> </strong></p>
        <% end %>
        <% if plane.notes_text %>
          <p><%= plane.notes_text %> </p>
        <% end %>
      </div>
      <div class="span6 school">
        <p><strong><%= plane.school.name.titleize %> </strong></p>
      </div>
    </div>
<% else %>
    <p><strong><%= plane.school.name.titleize %> </strong></p>
<% end %>
  
  

  </div>  
  <div class="span2"><h3><%= rental_text(plane.rental_amount) %> </h3></div>
</div>

app/views/planes/claim.html.erb
<!-- Lister details:

if no school association:
  name
  website
  email
  phone
  facebook page (?)
  
if school:
  preview school info
  prompt to add school
  

Billing details:

prompt for or verify billing info

select plan
  One year featured listing - $40
  Lifetime featured listing - $100


  Coupon code: [   ]


 information:

Use "Sawyer Aviation" information
Create a new school
Use  -->
<% provide(:title, "EasyPlaneRental.com - Claim Ownership for #{params[:id].upcase}") %>

<!-- sidebar -->
<div class="row-fluid">

  <div id="result-container" class="span10">
    
    <div id="result-header">
      <h4>Claim Ownership for <%= params[:id].upcase %></h4>
    </div>

    <div class="row-fluid">

      <%= simple_form_for(@plane, html: { :class => 'form-horizontal' }, remote: true) do |f| %>

      <div class="span11">
        <fieldset>
          <legend>Ownership Information</legend>
          <p>EasyPlaneRental.com allows every plane to have one owner.  Claiming a plane on behalf of a school or club provides several benefits:
            <ul>
              <li>Owners have exclusive access to maintaining plane information, ensuring information is up-to-date and relevant</li>
              <li>Owners can differentiate their plane by providing extra details like equipment descriptions, photos, and checkout requirements</li>
              <li>Owners can link to schedules and their company website to make it as painless as possible for renters</li>
            </ul>
          </p> 
        </fieldset>
      </div>
      
      <div id="plane-data" class="span5">
        <fieldset>
          <legend>School/Club Information</legend>
          
          <% if current_user.admin %>
            <%= f.input :school_id, collection: School.all, label: "Name" %>
          <% end %>

          <%= f.simple_fields_for :school do |s| %>
                <%= s.input :name %>
                <%= s.input :website %>
                <%= s.input :address, as: :text, input_html: { rows: 3 } %>
                <%= s.input :phone %>
                <%= s.input :email %>
                <%= s.input :base_airport %>
              </div>
          <% end %>
          
        </fieldset>
      </div>

      <div id="rental-data" class="span6">
        <fieldset>
          <legend>Account Information</legend>
          <% if @plane.featured? %>
            <p>This plane is owned and listed by <a href="<%= @plane.school.website %>" target="_blank"><%= @plane.school.name %></a>.</p>
            
            <div class="media">
              <a class="pull-left" href="<%= @plane.school.website || '#' %>" target="_blank">
                <img class="media-object" src="http://sawyeraviation.com/wp-content/uploads/2012/04/The-New-Sawyer-Logo-Horizon2.jpg">
              </a>
              <div class="media-body">
                <address>
                  <strong><%= @plane.school.name %></strong><br>
                  <%= "<a href='#{@plane.school.website}' target='_blank'>#{@plane.school.website}</a><br/>".html_safe if @plane.school.website.present? %>
                  <%= "#{@plane.school.address}<br/>".html_safe if @plane.school.address.present? %>
                  <%= "#{@plane.school.email}<br/>".html_safe if @plane.school.email.present? %>
                  <%= "#{@plane.school.phone}<br/>".html_safe if @plane.school.phone.present? %>
                </address>
              </div>
            </div>
            <% if current_user.school == @plane.school %>
              <p>Featured listing expires <%= @plane.featured_until %></p>
              <p><%= link_to "Click here", edit_school_path(@plane.school) %> to edit school information</p>
            <% else %>
              <p>A featured listing can only be edited by the owner.</p>
              <p>Something look incorrect?  <a href="#">Notify <%= @plane.school.name %>.</a></p>
            <% end %>
          <% elsif @plane.listing_incomplete? %>
            <p>The rental information for this plane may be incomplete.</p>
            <p>Please help the pilot community by improving this listing with any additional details you know.</p>
            <p><strong>Own/manage this plane?</strong> <%= link_to "Claim ownership", claim_plane_path(@plane) %> to add details, feature it, and get exclusive access to editing rental information.</p>
          <% else %>
            <p>The plane <%= @plane.tail_number %> does not yet appear to be listed.</p>
            <p>Know of rental details?  Please add them below to help the pilot community!</p>
            <p><strong>Own/manage this plane?</strong> <%= link_to "Claim ownership", claim_plane_path(@plane) %> to add details, feature it, and get exclusive access to editing rental information.</p>
          <% end %>

          <br/>
          <%= f.input :base_airport, input_html: { onblur: "value=value.toUpperCase();" } %>

          <div class="control-group">
            <label class="control-label" for="plane_rental_amount">Rental rate</label>
            <div class="controls control-row">
              <div class="input-prepend input-append inline span6">
                <span class="add-on">$</span>
                <input id="plane_rental_amount" class="span6" name="plane[rental_amount]" type="text" value="<%= @plane.rental_amount %>"/>
                <span class="add-on">per hr</span>
              </div>
              <select id="plane_rental_type" class="span3 inline" name="plane[rental_type]">
                <option <%= "selected='selected'" unless @plane.rental_type == "dry" %>>wet</option>
                <option <%= "selected='selected'" if @plane.rental_type == "dry" %>>dry</option>
              </select>
            </div>
          </div>
          <% if current_user.admin %>
            <%= f.input :school_id, collection: School.all, label_method: :name %>
          <% end %>
          <%= f.input :external_url %>
          <%= f.input :notes_text, as: :text, input_html: { :rows => 4 } %>
          <%= f.input :image_url, disabled: true %>
          
        </fieldset>
      </div>


      <div class="form-actions">
        <%= f.button :submit %>
      </div>
      
      <% end %>

    </div>

  </div>

  <div id="advertisement-container" class="span2">
    <div class="advertisement">
      Feature listing/school #1
    </div>
    <div class="advertisement">
      Feature listing/school #2
    </div>
    <div class="advertisement">
      Feature listing/school #3
    </div>
  </div>
  
</div>

app/views/planes/edit.html.erb
<%= render 'form' %>

app/views/planes/index.html.erb
<% provide(:title, 'Search Results') %>

<!-- sidebar -->
<div class="row-fluid">

  <div id="result-container" class="span10">
    
    <div id="result-header">
      <h4><%= pluralize(@planes.count, 'matching plane') %></h4>
    </div>

    <div class="row-fluid">

      <div id="filter-container" class="span3">
        <%= simple_form_for @filter, method: "get", url: planes_path do |f| %>
          <%= f.hidden_field :previous_query, value: @filter.query %>
          <%= f.input :query, label: false, input_html: { class: "span12" }, placeholder: "Airport or Tail Number" %>
          <%= f.button :submit, "Update filter" %>
          
          <% unless @endorsement_options.length < 1 %>
          <div class='filter-group'>
            <div class='hidden-actions pull-right'>
              <div>
                <a class='select-all'>all</a>
                <a class='select-none'>none</a>
              </div>
            </div>
            <legend>Endorsements</legend>
            <%= f.input :endorsements, collection: @endorsement_options, hidden_fields: false, label: false, as: :check_boxes %>
          </div>
          <% end %>
          
          <% unless @category_options.length < 1 %>
          <div class='filter-group'>
            <div class='hidden-actions pull-right'>
              <div>
                <a class='select-all'>all</a>
                <a class='select-none'>none</a>
              </div>
            </div>
            <legend>Categories</legend>
            <%= f.input :categories, collection: @category_options, label: false, as: :check_boxes %>
          </div>
          <% end %>
          
          <% unless @aircraft_type_options.length < 1 %>
          <div class='filter-group'>
            <div class='hidden-actions pull-right'>
              <div>
                <a class='select-all'>all</a>
                <a class='select-none'>none</a>
              </div>
            </div>
            <legend>Aircraft Types</legend>
            <%= f.input :aircraft_types, collection: @aircraft_type_options, label: false, as: :check_boxes %>
          </div>
          <% end %>
          
          <% unless @engine_type_options.length < 1 %>
          <div class='filter-group'>
            <div class='hidden-actions pull-right'>
              <div>
                <a class='select-all'>all</a>
                <a class='select-none'>none</a>
              </div>
            </div>
            <legend>Engine Types</legend>
            <%= f.input :engine_types, collection: @engine_type_options, label: false, as: :check_boxes %>
          </div>
          <% end %>
          
        <% end %>
      </div>

      <div id="list-container" class="span9">
        <table class="table table-hover table-condensed">
          <thead>
            <tr>
              <th>Tail</th>
              <th>Year</th>
              <th>Description</th>
              <th>Type</th>
              <th>Rental</th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <% @planes.each do |plane| %>
            <tr data-id="<%= plane.id %>">
              <td><%= plane.tail_number %></td>
              <td><%= plane.year %></td>
              <td><%= plane.manufacturer.titleize %> <%= plane.model %></td>
              <td><%= plane.abbreviated_type %></td>
              <td><%= plane.rental %></td>
              <td><a data-toggle="modal" href="<%= edit_plane_path(plane) %>" data-target="#edit-modal">Edit</a></td>
              <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>

        </table>

        <%= paginate @planes %>

        <a data-toggle="modal" href="<%= new_plane_path %>" data-target="#edit-modal">New Plane</a>

      </div>

    </div>

    <div id="edit-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Edit plane</h3>
      </div>
      <div class="modal-body">
        <p>Loading data…</p>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button class="btn btn-primary" id="edit-modal-submit">Save changes</button>
      </div>
    </div>

    <script>
      $('#edit-modal-submit').on('click', function(e){
        // We don't want this to act as a link so cancel the link action
        e.preventDefault();

        // Find form and submit it
        $('#edit-modal form').submit();
      });
      
      $(document).on('submit', '#edit-modal form', function() {  
          var valuesToSubmit = $(this).serialize();
          $.ajax({
              type: $(this).attr('method'),
              url: $(this).attr('action'), 
              data: valuesToSubmit
          }).success(function(json){
              $('#edit-modal').modal('hide');
          })
          return false; // prevents normal behaviour
      });
    </script>
    
  </div>

  <div id="advertisement-container" class="span2">
    <div class="advertisement">
      Feature listing/school #1
    </div>
    <div class="advertisement">
      Feature listing/school #2
    </div>
    <div class="advertisement">
      Feature listing/school #3
    </div>
  </div>
  
</div>

app/views/planes/new.html.erb
<%= render 'form' %>

app/views/planes/search.html.erb
<% provide(:title, 'Search Results') %>

<!-- sidebar -->
<div class="row-fluid">

  <div id="result-container" class="span10">
    
    <div id="result-header">
      <h4><%= pluralize(@planes.count, 'plane') %> near "<%= params[:filter][:query]%>"</h4>
    </div>

    <div class="row-fluid">

      <div id="filter-container" class="span3">
        <%= simple_form_for @filter, method: "get", url: 'search' do |f| %>
          <%= f.hidden_field :previous_query, value: @filter.query %>
          <%= f.input :query, label: false, input_html: { class: "span12" }, placeholder: "Airport or Tail Number" %>
          <%= f.button :submit, "Update filter" %>
          
          <% unless @endorsement_options.length < 1 %>
          <div class='filter-group'>
            <div class='hidden-actions pull-right'>
              <div>
                <a class='select-all'>all</a>
                <a class='select-none'>none</a>
              </div>
            </div>
            <legend>Endorsements</legend>
            <%= f.input :endorsements, collection: @endorsement_options, hidden_fields: false, label: false, as: :check_boxes %>
          </div>
          <% end %>
          
          <% unless @airport_options.length < 1 %>
          <div class='filter-group'>
            <div class='hidden-actions pull-right'>
              <div>
                <a class='select-all'>all</a>
                <a class='select-none'>none</a>
              </div>
            </div>
            <legend>Airports</legend>
            <%= f.input :airports, collection: @airport_options, label: false, as: :check_boxes %>
          </div>
          <% end %>
          
        <% end %>
      </div>

      <div id="list-container" class="span9">
        <!-- <table class="table table-hover table-condensed">
          <thead>
            <tr>
              <th>Tail</th>
              <th>Year</th>
              <th>Description</th>
              <th>Type</th>
              <th>Rental</th>
              <th></th>
            </tr>
          </thead>

          <% @planes.each do |plane| %>
            <tr data-id="<%= plane.id %>">
              <td><%= plane.tail_number %></td>
              <td><%= plane.year %></td>
              <td><%= plane.manufacturer.titleize %> <%= plane.model %></td>
              <td><%= plane.abbreviated_type %></td>
              <td><%= plane.rental %></td>
              <td><a data-toggle="modal" href="<%= plane_path(plane) %>" data-target="#show-modal">Details</a></td>
            </tr>
          <% end %>

        </table> -->

        <%= render @planes %>
        
        <%= paginate @planes %>
      </div>

    </div>

    <div id="show-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Plane Details</h3>
      </div>
      <div class="modal-body">
        <p>Loading data…</p>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
        <button class="btn btn-primary" id="show-modal-submit">Contact Owner</button>
      </div>
    </div>
    
  </div>

  <div id="advertisement-container" class="span2">
    <div class="advertisement">
      Feature listing/school #1
    </div>
    <div class="advertisement">
      Feature listing/school #2
    </div>
    <div class="advertisement">
      Feature listing/school #3
    </div>
  </div>
  
</div>

app/views/planes/show.html.erb
  <!-- <td><%= @plane.tail_number %></td>
  <td><%= @plane.name %></td>
  <td><%= @plane.base_airport %></td>
  <td><%= @plane.rental_amount %></td>
  <td><%= @plane.rental_type %></td>
  <td><a data-toggle="modal" href="<%= edit_plane_path(@plane) %>" data-target="#edit-modal">Edit</a></td>
  <td><%= link_to 'Destroy', @plane, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->

<!-- featured -->


<!-- non-featured -->
<!-- <th>Placehlder image</th>
<th>Manufacturer, name, model</th>
<th>School name</th>
<th>School name</th>
 -->

<%= render 'plane' %>