config/routes.rb
PlaneFinder::Application.routes.draw do
  devise_for :users
  resource :user do
    resources :planes
  end
  
  resources :schools
  
  resources :planes do
    get 'search', :on => :collection
    get 'claim', :on => :member
  end

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/legal',   to: 'static_pages#legal'
  match '/contact', to: 'static_pages#contact'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us</h1>
<p>
  This site aims to connect pilots with planes.  Whether you're a renter, flight school, buyer, or seller, visit frequently to connect with the aviation services you need.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  <a href="mailto:mikerrobinson@hotmail.com">Contact us</a> to talk flying, renting, owning, instructing, washing, or just watching airplanes.  We love this stuff and want to hear your story.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Teach me how to locate planes</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<style type="text/css">

      /* Main marketing message and sign up button */
      .landing-main {
        margin: 60px 0 20px 0;
        text-align: center;
      }

      .landing-main h2 { margin-bottom: 20px; }
      
</style>

<div class="container">
  
  <div class="landing-main">
    <h2>The best way to find or list planes for rent.</h2>
  </div>

  <div class="search-form">
    <%= form_tag search_planes_path, :method => 'get' do  %>  
      <div class="input-append">
          <%= text_field_tag :search, params[:search], class: "span6", placeholder: "Enter any location, airport ID, or tail number" %>
          <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
  
  <div class="row-fluid">
    <div class="span4 offset2 advertisement">
      <h4>Are you a renter?</h4>
      Know of local rentals?  Please take a moment to make sure they're listed and accurate:
      <%= form_tag planes_path, :method => 'get', :class => 'verify' do  %>  
      <div class="input-prepend input-append">
        <span class="add-on">N</span>
        <%= text_field_tag :tail_number, params[:id], class: "span5", placeholder: "Tail #", required: true, pattern: "^[1-9][0-9]{0,4}$|^[1-9][0-9]{0,3}[A-Za-z]$|^[1-9][0-9]{0,2}[A-Za-z]{2}$" %>
        <%= submit_tag "Verify plane", :name => "submit", class: "btn" %>
      </div>
      <% end %>
      <% unless user_signed_in? %>
        <%= link_to "Sign in", new_user_registration_path %> to see all rates, special deals, and save custom searches
      <% end %>
    </div>

    <div class="span4 advertisement">
      <h4>Are you an owner?</h4>
      Claim ownership of a listing to add details, feature it, and get exclusive access to editing that plane's information.
      <%= form_tag planes_path, :method => 'get', class: 'claim' do  %>  
      <div class="input-prepend input-append">
        <span class="add-on">N</span>
        <%= text_field_tag :tail_number, params[:id], class: "span5", placeholder: "Tail #", required: true, pattern: "^[1-9][0-9]{0,4}$|^[1-9][0-9]{0,3}[A-Za-z]$|^[1-9][0-9]{0,2}[A-Za-z]{2}$" %>
        <%= submit_tag "Claim plane", :name => "submit", class: "btn" %>
      </div>
      <% end %>
      <% unless user_signed_in? %>
        <%= link_to "Sign in", new_user_session_path %> to manage your listings
      <% end %>
    </div>
  </div>
  
  <div class="row-fluid">
    <div class="span8 offset2 advertisement">
      <h4>By pilots, for pilots</h4>
      Providing a complete and accurate database of planes for rent is why EasyPlaneRental.com exists.  We do our best to continuously update airplane data, but this site is best maintained by pilots, for pilots.  Please help by verifying that the rentals you've flown (or aspire to fly!) are listed by checking the tail number above.  Thank you and happy flying.</p>
    </div>
  </div>

</div>

app/views/static_pages/legal.html.erb
<% provide(:title, 'Legal') %>
<h1>Legal stuff</h1>
<p>
  blah blah blah
</p>