config/routes.rb
PlaneFinder::Application.routes.draw do
  devise_for :users
  resource :user do
    resources :planes
  end
  
  resources :schools
  
  resources :planes do
    get 'search', :on => :collection
    get 'claim', :on => :member
  end

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/legal',   to: 'static_pages#legal'
  match '/contact', to: 'static_pages#contact'

end

app/models/role.rb
class Role
  include Mongoid::Document
  
  has_and_belongs_to_many :users
  belongs_to :resource, :polymorphic => true
  
  field :name, :type => String
  index({ :name => 1 }, { :unique => true })


  index({
    :name => 1,
    :resource_type => 1,
    :resource_id => 1
  },
  { :unique => true})
  
  scopify
end

app/models/school.rb
class School
  include Mongoid::Document
  include Geocoder::Model::Mongoid
  resourcify
  
  geocoded_by :address               # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  
  attr_accessible :website, :phone, :address, :image_url, :base_airport, :name, :email, :user_ids, :plane_ids

  field :name, type: String
  field :website, :type => String
  field :email, :type => String
  field :phone, :type => String
  field :address, :type => String
  field :image_url, type: String
  field :base_airport, type: String  
  field :coordinates, :type => Array
  
  has_many :planes, inverse_of: :school
  has_many :users

  validates_presence_of :name
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schools }
    end
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @school = School.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/new
  # GET /schools/new.json
  def new
    @school = School.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @school }
    end
  end

  # GET /schools/1/edit
  def edit
    @school = School.find(params[:id])
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(params[:school])
    @school.user_ids = params[:school][:users] if params[:school][:users]
    
    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render json: @school, status: :created, location: @school }
      else
        format.html { render action: "new" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schools/1
  # PUT /schools/1.json
  def update
    @school = School.find(params[:id])
    @school.user_ids = params[:school][:users] if params[:school][:users]

    respond_to do |format|
      if @school.update_attributes(params[:school])
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school = School.find(params[:id])
    @school.destroy

    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= simple_form_for(@school) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :website %>
    <%= f.input :image_url, disabled: true %>
    <%= f.input :address, as: :text, input_html: { rows: 3 } %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.input :base_airport %>
    
    <% if current_user.admin %>
      <%= f.input :user_ids, collection: User.all, label_method: :email, input_html: { multiple: "multiple" }, include_blank: true %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<table class="table table-hover table-condensed">
  <caption><h3>All schools</h3></caption>
  <thead>
    <tr>
      <th>Name</th>
      <th>Website</th>
      <th>Phone</th>
      <th>Base airport</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

<% @schools.each do |school| %>
  <tr>
    <td><%= school.name %></td>
    <td><%= school.website %></td>
    <td><%= school.phone %></td>
    <td><%= school.base_airport %></td>
    <td><%= link_to 'Show', school %></td>
    <td><%= link_to 'Edit', edit_school_path(school) %></td>
    <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @school.name %>
</p>

<p>
  <b>Website:</b>
  <%= @school.website %>
</p>

<p>
  <b>Image url:</b>
  <%= @school.image_url %>
</p>

<p>
  <b>Phone:</b>
  <%= @school.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @school.email %>
</p>

<p>
  <b>Base airport:</b>
  <%= @school.base_airport %>
</p>


<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>

<p>
  <b>Planes</b>
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>Tail</th>
        <th>Year</th>
        <th>Description</th>
        <th>Type</th>
        <th>Rental</th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <% @school.planes.each do |plane| %>
      <tr data-id="<%= plane.id %>">
        <td><%= plane.tail_number %></td>
        <td><%= plane.year %></td>
        <td><%= plane.manufacturer.titleize %> <%= plane.model %></td>
        <td><%= plane.abbreviated_type %></td>
        <td><%= plane.rental %></td>
        <td><a data-toggle="modal" href="<%= edit_plane_path(plane) %>" data-target="#edit-modal">Edit</a></td>
        <td><%= link_to 'Destroy', plane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

  </table>
  
  <div id="edit-modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="myModalLabel">Edit plane</h3>
    </div>
    <div class="modal-body">
      <p>Loading data…</p>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <button class="btn btn-primary" id="edit-modal-submit">Save changes</button>
    </div>
  </div>
  
  <script>
    $('#edit-modal-submit').on('click', function(e){
      // We don't want this to act as a link so cancel the link action
      e.preventDefault();

      // Find form and submit it
      $('#edit-modal form').submit();
    });
    
    $(document).on('submit', '#edit-modal form', function() {  
        var valuesToSubmit = $(this).serialize();
        $.ajax({
            type: $(this).attr('method'),
            url: $(this).attr('action'), 
            data: valuesToSubmit
        }).success(function(json){
            $('#edit-modal').modal('hide');
        })
        return false; // prevents normal behaviour
    });
  </script>
  
</p>