config/routes.rb
PlaneFinder::Application.routes.draw do
  devise_for :users
  resource :user do
    resources :planes
  end
  
  resources :schools
  
  resources :planes do
    get 'search', :on => :collection
    get 'claim', :on => :member
  end

  root to: 'static_pages#home'
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/legal',   to: 'static_pages#legal'
  match '/contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Legal",   legal_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
  <p>
    <small>© Samir and Mike 2012</small>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
  
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to t(:site_name), root_path, class: "brand" %>
      <div class="nav-collapse">
        <ul class="nav pull-right">
        
          <% if user_signed_in? %>
            <% if current_user.admin %>
              <li><%= link_to "Schools", schools_path %></li>
  				    <li><%= link_to "Planes", planes_path %></li>
  				  <% else %>
				      <li><%= link_to "My Planes", user_planes_path %></li>
            <% end %>
            <li><%= link_to "Settings", edit_user_registration_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Sign out", destroy_user_session_path, method: "delete" %>
            </li>
          <% else %>
            <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
          
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= t(:site_name) %> | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
  <body>
    
    <div id="wrap">

      <!-- Begin page content -->
      <div class="container">
        <%= render "layouts/header" %>

        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= content_for?(:content) ? yield(:content) : yield %>
      </div>

      <div id="push"></div>
    </div>

    <div id="footer">
      <div class="container">
        <%= render 'layouts/footer' %>
      </div>
    </div>
    
  </body>
</html>

app/views/layouts/users.html.erb
<% content_for :content do %>

<!-- sidebar -->
<div class="row-fluid">

  <div id="result-container" class="span12">
    
    <div id="result-header">
    </div>

    <div class="row-fluid">

      <div class="span12">
        <%= yield %>
      </div>
      
    </div>

  </div>

</div>

<% end %>
<%= render :template => 'layouts/application' %>